// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCM8WdY3ZzqP6ByXf3B5D3V3L4KhxUY-o4',
    appId: '1:900231556865:web:d16fed86070055236db500',
    messagingSenderId: '900231556865',
    projectId: 'smart-education-ac5bd',
    authDomain: 'smart-education-ac5bd.firebaseapp.com',
    storageBucket: 'smart-education-ac5bd.appspot.com',
    measurementId: 'G-DV9V6ZRL3L',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBFxWuv-oMPJ67h58NtxA6JK3H2FXqWAAE',
    appId: '1:900231556865:android:d359f951561f4d966db500',
    messagingSenderId: '900231556865',
    projectId: 'smart-education-ac5bd',
    storageBucket: 'smart-education-ac5bd.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCCUoX667XdkTmUSnKQl9BHvZxpO66fc0k',
    appId: '1:900231556865:ios:98a84f62b51f91726db500',
    messagingSenderId: '900231556865',
    projectId: 'smart-education-ac5bd',
    storageBucket: 'smart-education-ac5bd.appspot.com',
    iosBundleId: 'com.example.smartEducation',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCCUoX667XdkTmUSnKQl9BHvZxpO66fc0k',
    appId: '1:900231556865:ios:576b0a434723b6996db500',
    messagingSenderId: '900231556865',
    projectId: 'smart-education-ac5bd',
    storageBucket: 'smart-education-ac5bd.appspot.com',
    iosBundleId: 'com.example.smartEducation.RunnerTests',
  );
}
